# Generated by Django 3.2.9 on 2023-04-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='max_puntaje',
            field=models.IntegerField(default=1, verbose_name='Maximo Puntaje'),
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('level', models.CharField(choices=[('basic', 'BASIC'), ('intermediate', 'INTERMEDIATE'), ('advance', 'ADVANCE')], default='basic', max_length=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.categorymodel')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['id'],
            },
        ),
    ]
