# Generated by Django 3.2.9 on 2023-05-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_remove_coursesectionmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetVocavularyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='VocavularyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursesectionmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='quizUser',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='quizuser',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CourseModel',
        ),
        migrations.DeleteModel(
            name='CourseSectionModel',
        ),
        migrations.DeleteModel(
            name='PreguntasRespondidas',
        ),
        migrations.DeleteModel(
            name='QuizUser',
        ),
        migrations.AddField(
            model_name='detvocavularymodel',
            name='vocavulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.vocavularymodel'),
        ),
    ]
