# Generated by Django 3.2.9 on 2023-05-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_auto_20230513_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detvocavularymodel',
            old_name='categor',
            new_name='category',
        ),
    ]
