# Generated by Django 3.2.9 on 2023-05-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_rename_categor_detvocavularymodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColVocavularyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
            ],
        ),
    ]
