# Generated by Django 3.2.9 on 2023-05-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_colvocavularymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='colvocavularymodel',
            name='vocavulary',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.vocavularymodel'),
            preserve_default=False,
        ),
    ]
