# Generated by Django 3.2.9 on 2023-05-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0008_colvocavularymodel_vocavulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colvocavularymodel',
            name='vocavulary',
        ),
        migrations.AddField(
            model_name='vocavularymodel',
            name='colvocavulary',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.colvocavularymodel'),
            preserve_default=False,
        ),
    ]
