# Generated by Django 3.2.9 on 2023-05-14 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0009_auto_20230513_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocavularymodel',
            name='colvocavulary',
        ),
        migrations.AddField(
            model_name='colvocavularymodel',
            name='vocavulary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.vocavularymodel'),
            preserve_default=False,
        ),
    ]
